apiVersion: v1
kind: Service
metadata:
  name: lender-api
  namespace: lender
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "classic"
spec:
  type: LoadBalancer
  selector:
    app: lender-api
  ports:
    - port: 80
      targetPort: 3001
